<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/17 01:53:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/tmp/sf_sandbox/data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
