<?php

/**
 * PlaylistItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaylistItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlaylistItem');
    }
}