
indexSuccess:
  stylesheets:    [theme.css, jplayer.vkplayer.css]
  javascripts:    [jsCoreExt.js, jquery-1.4.4.js, jquery-ui-1.8.6.custom.js, jquery.jplayer.js, vkLibrary.js, siteMenu.js, vkPlayer.js, http://vkontakte.ru/js/api/openapi.js, vkAPI.js, main.js]
  has_layout:     true
  layout:         vkplayer
